- client/.eslintrc.json
**개요**
eslint 기능 추가 및 src 내부 디렉토리 수정
**타입**
**작업 사항**
- eslint : prietter plugin 추가, 
- src 내부 폴더 디렉토러 설정 
-  components : 각 세부 컴포넌트를 분리해서 작성, 스타일링 파일은 따로 분리한다(.styles.jsx)
- apis : API 호출 관련된 로직이나 토큰 키 등 관리
- pages : 최종 보여질 페이지 구현 - 최종 컴포넌트 합침
- mocks : 객체 데이터 관리
- styles: flex, button, input, hidden, reset 등 전역 스타일 정의
- theme: 전역 스타일 변수 정의 (색상 등)
- utils - random 등 프론트에서 수행하는 연산 작업 함수 관리
> style: eslint 기능 추가 및 src 내부 디렉토리 수정

- server/src/test/java/com/watchtogether/server/ServerApplicationTests.java
**개요**
pr 테스트를 위한 커밋 및 pr
**타입**
**작업 사항**
pr 테스트를 위한 커밋 및 pr
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> test : pr 테스트를 위한 커밋

- client/package-lock.json
- client/package.json
- client/src/index.js
- client/src/styles/Button.jsx
- client/src/styles/Common.jsx
- client/src/styles/Flex.jsx
- client/src/styles/Input.jsx
- client/src/styles/reset.css
- client/src/styles/theme/theme.js
**개요**
전역 스타일 추가 
eslint prettier 재설정 
**타입**
**작업 사항**
- theme : 색상 변수 추가 
- button, flex, input, reset.css 전역 스타일 파일 추가 
**Test**🧪
> feat: 전역 스타일 파일 추가

- server/src/test/java/com/watchtogether/server/ServerApplicationTests.java
**개요**
test : pr 테스트를 위한 커밋 및 pr2
**타입**
**작업 사항**
test : pr 테스트를 위한 커밋 및 pr2
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> test : pr 테스트를 위한 커밋2

- server/src/test/java/com/watchtogether/server/ServerApplicationTests.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> test : pr 테스트를 위한 커밋4

- server/build.gradle
- server/src/main/java/com/watchtogether/server/config/SwaggerConfig.java
- server/src/main/resources/application.yml
**개요**
feat : SwaggerConfig 파일 추가 및 작성
bulid : Swagger 의존성 추가
**타입**
**작업 사항**
feat : SwaggerConfig 파일 추가 및 작성
bulid : Swagger 의존성 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : SwaggerConfig 파일 추가 및 작성  및 bulid : Swagger 의존성 추가

- client/src/App.js
- client/src/components/Header/Header.jsx
- client/src/components/Header/Header.styles.jsx
- client/src/components/Header/Logo.jsx
- client/src/components/Main/Main.jsx
- client/src/components/Main/Main.style.jsx
- client/src/index.js
- client/src/mocks/icons.js
- client/src/pages/MainPage.jsx
**개요**
메인 페이지 구현
**타입**
**작업 사항**
- 헤더 컴포넌트 구현 
- 메인 컴포넌트 구현
- 메인 페이지 구현 
< 스크린샷 > 
**Test**🧪
> feat: 메인 페이지 구현 

- server/src/main/resources/application.yml
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : 서버포트 양식 수정 및 프로젝트 구조 패키지 생성

- chatServer/src/main/java/com/example/sockettest/api/ChatController.java
- chatServer/src/main/java/com/example/sockettest/domain/ChatRoom.java
- chatServer/src/main/java/com/example/sockettest/domain/CreateRoomRequest.java
- chatServer/src/main/java/com/example/sockettest/service/ChatService.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- (수정 전) 채팅방 생성 api로 채팅방을 생성하면 roomId를 리턴.
- (수정 후) 채팅방 생성 api로 채팅방 생성 시 roomId를 직접 입력. 
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 채티방 생성 api 수정

- README.md
- client/.eslintrc.json
- client/public/index.html
- client/src/App.js
- client/src/components/Header/Header.styles.jsx
- client/src/components/Main/Main.jsx
- client/src/components/Main/Main.style.jsx
- client/src/pages/MainPage.jsx
- client/src/styles/Button.jsx
- client/src/styles/Common.jsx
- client/src/styles/Input.jsx
- client/src/styles/reset.css
**개요**
셋업 수정 및 메인 페이지 수정 
**타입**
**작업 사항**
초기 셋업 
- Eslint 기능 추가 
- 기본 폰트 변경 
- 전역 스타일 수정 
메인페이지 수정 
- 링크 변경 : Link -> useNavigate 사용 
- 태그 변경 : div -> header 
- 헤더 위치 변경 :  Routes -> MainPage
**Test**🧪
> fix: 셋업 수정 및 메인 페이지 수정 

- client/package-lock.json
- client/package.json
- client/src/components/Header/LoginHeader.jsx
- client/src/components/Header/LoginHeader.styles.jsx
- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.styles.jsx
- client/src/pages/LoginPage.jsx
**개요**
로그인 페이지 틀 제작  (기능 추가전) 
**타입**
**작업 사항**
- 로그인 헤더 컴포넌트 -> React-icons 설치
- 로그인 컴포넌트 
- 로그인 페이지 제작 
**Test**🧪
> feat: 로그인 페이지 틀 제작 

- chatServer/build.gradle
- chatServer/src/main/java/com/example/sockettest/api/ChatController.java
- chatServer/src/main/java/com/example/sockettest/config/WebSocketHandler.java
- chatServer/src/main/java/com/example/sockettest/domain/ChatRoom.java
- chatServer/src/main/java/com/example/sockettest/domain/DialogDto.java
- chatServer/src/main/java/com/example/sockettest/persist/DialogRespository.java
- chatServer/src/main/java/com/example/sockettest/persist/entity/Dialog.java
- chatServer/src/main/java/com/example/sockettest/service/ChatService.java
- chatServer/src/main/resources/application.yml
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 대화내용 디비에 저장 가능하게 구현
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> 대화내용 디비에 저장 가능하게 구현

- client/src/App.js
- client/src/components/Mypage/MypageHeader.jsx
- client/src/components/Mypage/MypageHeader.styles.jsx
- client/src/components/Mypage/Profile.jsx
- client/src/components/Mypage/Profile.styles.jsx
- client/src/components/Mypage/User.jsx
- client/src/components/Mypage/User.styles.jsx
- client/src/pages/MyPage.jsx
**개요**
마이페이지 구현 -> 기능 추가 전 틀 잡기
**타입**
**작업 사항**
- 마이페이지 라우터 연결 
- 헤더 및 컨텐츠 컴포넌트 추가 
- 
**Test**🧪
> feat: 마이페이지 구현 

- server/build.gradle
- server/src/main/java/com/watchtogether/server/components/MailComponents.java
- server/src/main/java/com/watchtogether/server/config/MailConfig.java
- server/src/main/java/com/watchtogether/server/config/SwaggerConfig.java
- server/src/main/java/com/watchtogether/server/users/controller/UsersController.java
- server/src/main/java/com/watchtogether/server/util/YamlPropertySourceFactory.java
- server/src/main/resources/application.yml
- server/src/test/java/com/watchtogether/server/components/MailComponentsTest.java
**개요**
- 회원가입시 필요한 인증 이메일 보내기 기능 추가
- yml 파일을 읽기 위한 util 추가 후, 보안 이슈가 발생 할 수 있는 password의 노출을 제거 함
**타입**
**작업 사항**
- dependency_spring-boot-starter-mail 을 추가
- JavaMailSender으로 인증 이메일 보내기 기능 추가
**Test**🧪
- 간단한 테스트 내용
- 인증 이메일 보내기 성공 케이스
- 인증 이메일 보내기 실패 케이스
- 테스트 의도
- 인증 이메일 보내기 기능이 제대로 작동하는지 확인하기 위해
> feat : 인증 이메일 보내기 기능 추가

- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.styles.jsx
**개요**
feat: 로그인 validate 기능 추가
**타입**
**작업 사항**
- 로그인시 아이디와 비밀번호 유효한지 체크하는 함수 추가 
- 유효하지 않을 경우, 보여주는 error 메시지 추가 
- 스타일 수정 
**Test**🧪
> feat: 로그인 validate 기능 추가

- server/src/main/java/com/watchtogether/server/exception/type/ErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/VerifyEmail.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
- server/src/main/resources/application.yml
- server/src/test/java/com/watchtogether/server/users/controller/UserControllerTest.java
**개요**
- 인증 메일 검증 및 승인 기능 추가
- 회원가입 신청 기능 버그  수정
**타입**
**작업 사항**
- 회원가입 신청 후 전송된 인증 메일을 검증하는 기능 추가
- 검증 후 정상적인 데이터인 경우 이메일 인증 확인 기능 추가
- 잘 못 입력된 USER관련 ENUM 파일 수정
**Test**🧪
- 인증 메일 검증 API 테스트
> feat : 인증 메일 검증 및 승인 기능 추가

- server/src/main/resources/application.yml
**개요**
build  : server 포트 8080 -> 8081
**타입**
**작업 사항**
build  : server 포트 8080 -> 8081
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> build  : server 포트 8080 -> 8081

- chatServer/src/main/java/com/example/sockettest/config/WebConfig.java
- server/src/main/java/com/watchtogether/server/config/WebConfig.java
- server/src/main/java/com/watchtogether/server/exception/PartyException.java
- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/AcceptPartyForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/partyService.java
**개요**
feat : 파티 초대링크 수락시 파티테이블 파티인원수 증가
**타입**
**작업 사항**
- 파티 초대링크 수락시 파티테이블 파티인원수 증가
- 초대repository 생성
- 파티부분 error 종류생성
**Test**🧪
- 간단한 테스트 내용
- 초대링크 클릭시 uuid, 인증시간, 닉네임이 맞지 않을시 오류출력
> feat : 파티 초대링크 수락시 파티테이블 파티인원수 증가

- server/src/main/java/com/watchtogether/server/exception/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/exception/ExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/PartyException.java
- server/src/main/java/com/watchtogether/server/exception/UserException.java
- server/src/main/java/com/watchtogether/server/exception/type/UserErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/dto/UserDto.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/User.java
- server/src/main/java/com/watchtogether/server/users/domain/model/SignInUser.java
- server/src/main/java/com/watchtogether/server/users/domain/model/SignUpUser.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserStatus.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
- server/src/test/java/com/watchtogether/server/users/controller/UserControllerTest.java
- server/src/test/java/com/watchtogether/server/users/service/impl/UserServiceImplTest.java
- server/src/test/resources/application.yml
**개요**
- 인증 이메일에 대한 검증 후, 로그인 처리
**타입**
**작업 사항**
- 이메일과 비밀번호를 입력 받고, 인증된 사용자인지 검증 후 정상적인 로그인 처리 기능
- SQL 키워드 중 USER가 있어서, USER 테이블 명을 USERS로 변경
- 별도로 구분 짓기 위해 ErrorCode 패키지 명을, UserErrorCode로 변경
- 테스트 환경을 고려해서,테스트 용 application.yml 파일 수정
**Test**🧪
- 사용자 로그인 API 테스트 ✔
- 사용자 로그인 테스트 코드 ✔
- 성공_로그인 처리
- 실패_일치하는 사용자 없는 경우
- 실패_패스워드가 일치하지 않는 경우
- 실패_탈퇴한 사용자인 경우
- 실패_이메일을 인증 안한 경우
> feat : 사용자 로그인 기능 추가

- client/package-lock.json
- client/package.json
- client/src/components/Login/Login.jsx
- client/src/setupProxy.js
**개요**
feat: 로그인 사용자 확인 기능 추가 
**타입**
**작업 사항**
- 서버 데이터 전송을 통한 기존 사용자 여부 확인 및 에러 메시지 송출 기능 추가 
- 기존 서버에 대한 Proxy 서버 추가 
**Test**🧪
> feat: 로그인 사용자 확인 기능 추가 

- server/build.gradle
- server/src/main/java/com/watchtogether/server/components/mail/MailComponents.java
- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/config/mail/MailConfig.java
- server/src/main/java/com/watchtogether/server/config/swagger/SwaggerConfig.java
- server/src/main/java/com/watchtogether/server/exception/AuthExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/AuthenticationEntryPointHandler.java
- server/src/main/java/com/watchtogether/server/exception/type/AuthErrorCode.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
- server/src/test/java/com/watchtogether/server/components/MailComponentsTest.java
- server/src/test/java/com/watchtogether/server/users/service/impl/UserServiceImplTest.java
**개요**
- spring-security 기본 세팅 및 기능 추가
**타입**
**작업 사항**
- spring-security 기본 세팅 과 401 UNAUTHORIZED 예외 처리 handler를 구축
**Test**🧪
- 에러 없이 서버 구동 성공
- API 테스트 완료
- 401 UNAUTHORIZED 예외 처리 테스트 완료
> feat : spring-security 기능 추가

- chatServer/src/main/java/com/example/sockettest/api/ChatController.java
- chatServer/src/main/java/com/example/sockettest/domain/DeleteRoomRequest.java
- chatServer/src/main/java/com/example/sockettest/domain/DialogDto.java
- chatServer/src/main/java/com/example/sockettest/domain/GetDialogRequest.java
- chatServer/src/main/java/com/example/sockettest/persist/DialogRespository.java
- chatServer/src/main/java/com/example/sockettest/service/ChatService.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 대화 내용 조회 기능 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat: 대화내용 조회기능 추가

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Login/Login.jsx
- client/src/components/Mypage/Profile.jsx
- client/src/redux/store.js
- client/src/redux/user.js
**개요**
feat: 로그인 기능 추가 
fix: 로그인 기능 에러 수정 
**타입**
**작업 사항**
기능 추가
- 로그인에 성공할 경우, User 정보 상태 변경 -> Redux 
- 로그인 성공 시 mypage로 url 이동 (임시) 
- 변경된 User state로 마이 페이지 데이터 변경 
기능 수정 
- 아이디, 비밀번호를 정확하게 입력할 경우, 동작 하지 않는 이슈 수정 
**Test**🧪
> feat: 로그인 기능 추가

- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
feat : 패스워드 암호화 기능 추가
**타입**
**작업 사항**
- 회원가입시 패스워드 암호화
- 로그인시 패스워드와 암호화된 패스워드 matches
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 패스워드 암호화 기능 추가

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/components/SignIn/SignIn.jsx
- client/src/pages/SignInPage.jsx
**개요**
chore: 로그인 경로 수정 
**타입**
**작업 사항**
- 로그인 경로 수정 
- props type 설치 
**Test**🧪
> chore: 로그인 경로 수정 

- client/src/App.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/AddParty/AddParty.styles.jsx
- client/src/components/AddParty/AlertModal.jsx
- client/src/components/AddParty/AlertModal.styles.jsx
- client/src/components/AddParty/SearchModal.jsx
- client/src/components/AddParty/SearchModal.styles.jsx
- client/src/pages/AddPartyPage.jsx
**개요**
파티 모집글 작성 페이지 구현 
**타입**
**작업 사항**
- 모집글 form 구현 
- 파티원 검색 및 추가 모달 구현 
- alert 모달 구현 
**Test**🧪
- 간단한 테스트 내용
모집 글 폼 
파티원 검색 모달 
모집 글 등록 모달
> feat: 파티 모집글 작성 페이지 구현 

- server/build.gradle
- server/src/main/java/com/watchtogether/server/components/jwt/JwtAuthenticationFilter.java
- server/src/main/java/com/watchtogether/server/components/jwt/TokenProvider.java
- server/src/main/java/com/watchtogether/server/config/AppConfig.java
- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/exception/AuthExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/AuthenticationEntryPointHandler.java
- server/src/main/java/com/watchtogether/server/exception/type/AuthErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/dto/UserDto.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/User.java
- server/src/main/java/com/watchtogether/server/users/domain/model/SignInUser.java
- server/src/main/java/com/watchtogether/server/users/domain/type/Authority.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
feat : security jwt 기능 추가
**타입**
**작업 사항**
- 토큰 서명 값 생성 기능 추가
- 토큰 필터를 통한 인증 검사 기능 추가
- 토큰 인증 값 유효성 검사 에러 처리 기능 추가
**Test**🧪
- JWT API 테스트 완료
- 토큰 값 없음, 토큰 값 만료, 토큰 서명 값 불일치 예러 처리 API 테스트 완료
- https://beemiel.tistory.com/m/11
> feat : security jwt 기능 추가

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.js
- client/src/store/User.js
- client/src/store/index.js
**개요**
네이밍 변경 및 위치 변경 
**타입**
**작업 사항**
- 리액트 쿼리 삭제
- 폴더 이름 변경 : redux -> store
- provider 위치 변경 : App.js -> index.js 
**Test**🧪
> chore :  네이밍 변경 및 위치 변경 

- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/exception/UserException.java
- server/src/main/java/com/watchtogether/server/exception/handler/AuthenticationEntryPointHandler.java
- server/src/main/java/com/watchtogether/server/exception/handler/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/exception/response/AuthExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/response/UserExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/type/UserErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
chore : user api url 및 에러 메시지 형식 변경 
**타입**
**작업 사항**
- 에러 메시지 형식 변경(에러 상태코드 추가)
- 버전 관리를 위해 user api url에 v1 추가
- /api/v1/**
**Test**🧪
- users api 전체 테스트 완료
> chore : user api url 및 에러 메시지 형식 변경 

- server/src/main/java/com/watchtogether/server/exception/PartyException.java
- server/src/main/java/com/watchtogether/server/exception/handler/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/exception/response/PartyExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/BaseEntity.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- api명 수정
-  party에러메시지 수정
- base엔티티 추가로 인한 생성날짜와 수정날짜 자동화
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat :  base엔티티 추가로 인한 생성날짜와 수정날짜 자동화 chore : api명 수정 및party에러메시지 수정 

- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- chore : 필요하지 않은부분 삭제요.
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : 필요하지 않은부분 삭제

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
chore : PartyService -> PartyServiceImpl 로 가독성 좋게수정
**타입**
**작업 사항**
- chore : PartyService -> PartyServiceImpl 로 가독성 좋게수정
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : PartyService -> PartyServiceImpl 로 가독성 좋게수정

- client/src/api/Parties.js
- client/src/api/Users.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/SignIn/SignIn.jsx
**개요**
Api 관련 내용 수정 및 추가 
**타입**
**작업 사항**
- 파티 모집 컴포넌트 api 함수 분리
- 파티 모집 컴포넌트 axios body 속성 추가 -> leaderNickName
- Api url 수정 -> version 추가 
**Test**🧪
> fit: Api 관련 내용 수정 

- client/src/components/SignUp/SignUp.jsx
**개요**
fix: 회원가입 제출 기능 수정
**타입**
**작업 사항**
- 백엔드 서버와 연동하여 회원가입 제출 기능이 잘 실행되는지 확인해보았습니다.
- 기존 코드에서 'birth' 데이터의 타입이 string으로 되어 있어서 이를 date 타입으로 수정했는데, 수정 후 정상적으로 post한 데이터가 백엔드 서버로 넘어가는 것을 확인할 수 있었습니다.
- toastify 라이브러리를 통해 회원가입 완료시, 성공과 오류 상태의 메시지를 알림으로 보여줄 수 있게 구현했습니다.
**Test**🧪
> fix: 회원가입 제출 기능 수정

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/FindMyPartiesForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyMemberRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 자신이 속한 파티를 검색할수 있는 기능 구현
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
- ![image](https://user-images.githubusercontent.com/56632643/198635118-e81ca80c-da7c-4d34-94b1-e7fdc2d3a3b3.png)
> feat : 내가 속한 파티찾기 기능 구현 , chore : repository 어노테이션 추가

- server/src/main/java/com/watchtogether/server/components/jwt/JwtAuthenticationFilter.java
- server/src/main/java/com/watchtogether/server/exception/response/UserExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/type/UserErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/MyPageUser.java
- server/src/main/java/com/watchtogether/server/users/domain/model/SearchUser.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/UserRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- feat : 사용자 닉네임 검색 기능 추가
- chore : class명, 변수명 및 불필요한 import 제거
**타입**
**작업 사항**
- 파티 모집 글 작성시, 초대할 사용자 닉네임 검색 기능 추가
- 전체 닉네임으로 정확하게 검색, 아닐 시 에러 발생
- 불필요한 import 값들 제거
- 에러 메시지 변수 명 Message 에서 message로 변경
- model 패키지에 myPageUser class명을 MyPageUser로 변경
**Test**🧪
- 초대할 사용자 닉네임 검색 API 테스트 
> feat : 사용자 닉네임 검색 기능 추가

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/JoinPartyForm.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
feat : 파티참가 기능 추가, chore : 에러코드 추가 및 변수명 변경
**타입**
**작업 사항**
-  사용자의 닉네임과 들어가고자 하는 파티id를 받아서 파티참가 기능 구현
- 파티의 정원이 모두 찼을때 에러코드 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 파티참가 기능 추가, chore : 에러코드 추가 및 변수명 변경

- client/src/api/Parties.js
- client/src/api/Users.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/AddParty/SearchModal.jsx
- client/src/components/AddParty/SearchModal.styles.jsx
**개요**
파티 모집 form - 파티원 검색 기능 구현
**타입**
**작업 사항**
Api 수정 
- api 공통 경로 base_url로 변수 분리 
- version 추가 (v1) 
파티원 검색 기능 구현
- input value warning 수정 
- 뒤로가기 버튼 추가 
- 스타일 일부 수정
- 닉네임 검색 기능 , 서버 테스트 완료 
**Test**🧪
> feat: 파티 모집 form - 파티원 검색 기능 구현

- server/src/main/java/com/watchtogether/server/components/jwt/TokenProvider.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/ChangePassword.java
- server/src/main/java/com/watchtogether/server/users/domain/model/CheckPassword.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- feat : 새로운 패스워드로 변경 기능 추가
- feat : 현재 패스워드 검사 기능 추가
- chore : 토큰 값 유효시간 1시간으로 연장
**타입**
**작업 사항**
- 패스워드를 변경하기 전 현재 패스워드 검사 기능 추가
- 새로운 패스워드로 변경 기능 추가
- 토큰 값 유효시간 1시간으로 연장
**Test**🧪
- 패스워드 검사 및 변경 API 테스트
> feat : 새로운 패스워드로 변경 및 현재 패스워드 검사 기능 추가

- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/config/swagger/SwaggerConfig.java
**개요**
- chore : swagger 설정 추가
- fix : swagger 에러 수정
**타입**
**작업 사항**
1. jwt token 테스트를 위한 Authorize 헤더 기능 추가
2. anyRequest().authenticated() 추가 시 swagger 에러 수정
- web.ignoreing()에 "/api-docs/**" 경로 추가 함으로써 security filter에 걸리지 않는다
**Test**🧪
- swagger 기동 테스트
> chore : swagger 설정 추가

- server/src/main/java/com/watchtogether/server/components/mail/MailComponents.java
- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/User.java
- server/src/main/java/com/watchtogether/server/users/domain/model/AuthResetPassword.java
- server/src/main/java/com/watchtogether/server/users/domain/model/ResetNewPassword.java
- server/src/main/java/com/watchtogether/server/users/domain/model/ResetPassword.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/UserRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- feat : 비밀번호 초기화 코드 메일 전송 기능 추가
- chore : 비밀번호 초기화 키 및 패스워드 초기화 유효기간 추가
- feat : 비밀번호 초기화 및 변경 기능 추가
**타입**
**작업 사항**
- 비밀번호 초기화를 위한 entity 값 추가
- resetPasswordKey(재설정 비밀번호 키 값)
- resetPasswordLimitDt(재설정 비밀번호 유효기간)
- 비밀번호 초기화 인증 코드 메일 전송 기능 추가
- 비밀번호 초기화 인증 코드 검증 기능 추가
- 새로운 비밀번호로 변경 기능 추가
**Test**🧪
- 비밀번호 초기화 및 변경 기능 API 테스트
- ![ERD](https://user-images.githubusercontent.com/36691759/198890314-a4fa05fa-9e61-4c40-92c3-a421656ae12d.png)
- ![API 명세서](https://user-images.githubusercontent.com/36691759/198891206-6066e50b-fdc2-48b9-b3dd-f553cff700f6.png)
> feat : 비밀번호 초기화 및 변경 기능 추가

- server/src/main/java/com/watchtogether/server/components/mail/MailComponents.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/ResetNewPassword.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- refactor : 회원가입 인증 코드 메일 전송 api 를 Mailcomponents 파일로 이동
- chore : swagger 설정 정리 및 수정
**타입**
**작업 사항**
- email 관련 API는 한 곳에서 관리하기위해 mail 패키지로 이동
- model 패키지의 ResetNewPassword @Schema(name) 설정 변경
- UserController의 @Operation(summary) 부분 정리
**Test**🧪
- 전체 API 테스트 
> refactor: 회원가입 인증 코드 메일 전송 api 를 mail 패키지로 이동 

- client/package-lock.json
- client/package.json
- client/src/api/Parties.js
- client/src/api/Users.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/AddParty/AddParty.styles.jsx
- client/src/components/AddParty/SearchModal.styles.jsx
- client/src/components/SignIn/SignIn.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/index.js
**개요**
feat: Api 함수 추가 및 React-query 설치
chore: Prettier 
**타입**
**작업 사항**
- React-query 설치
- Api url 함수 추가 
- Prettier로 인한 변경 사항 -> 코드 변경 X 
**Test**🧪
> feat: Api 함수 추가 및 React-query 설치

- server/src/main/java/com/watchtogether/server/components/mail/MailComponents.java
**개요**
- fix : 패스워드 초기화 인증 코드 수정
**타입**
**작업 사항**
- 패스워드 초기화 인증 코드 링크 클릭시, 포론트엔드로 코드값을 전달
- 그 후에 포론트에서 패스워드 초기화 인증 코드 검증 API 요청
**Test**🧪
- 패스워드 초기화 인증 코드 API 테스트
> fix : 패스워드 초기화 인증 코드 수정

- client/src/components/Mypage/User.jsx
- client/src/components/Mypage/User.styles.jsx
- client/src/pages/AddPartyPage.jsx
- client/src/store/Auth.js
- client/src/utils/Cookie.js
**개요**
일부 기능 추가 
**타입**
**작업 사항**
- 마이페이지 - 내 정보 관리 추가
- 파티 모집 폼 헤더 추가  
- Cookie token 만료 일자 추가 
**Test**🧪
> feat: 일부 기능 추가 

- client/src/App.js
- client/src/components/UserInfo/AlertModal.jsx
- client/src/components/UserInfo/ChangeModal.jsx
- client/src/components/UserInfo/Modal.style.jsx
- client/src/components/UserInfo/UserInfo.jsx
- client/src/components/UserInfo/UserInfo.style.jsx
- client/src/pages/UserInfoPage.jsx
**개요**
내 정보 관리 페이지 구현 
**타입**
**작업 사항**
내 정보 관리 페이지 기능 구현
- 비밀번호 변경
- 로그아웃
- 회원 탈퇴 (마크업)
**Test**🧪
> feat: 내 정보 관리 페이지 구현 

- client/src/components/SignUp/SignUp.jsx
**개요**
feat: 회원가입 비밀번호 유효성 검사 기능 추가
**타입**
**작업 사항**
- 회원가입 비밀번호 유효성 검사를 추가했습니다.
- toast 알림 사라지는 속도를 조정했습니다.
**Test**🧪
> feat: 회원가입 비밀번호 유효성 검사 기능 추가

- client/src/api/Users.js
- client/src/components/UserInfo/AlertModal.jsx
- client/src/components/UserInfo/ChangeModal.jsx
- client/src/components/UserInfo/UserInfo.jsx
- client/src/components/UserInfo/UserInfo.style.jsx
**개요**
fix: 내 정보 관리 기능 수정 
**타입**
**작업 사항**
회원 탈퇴 기능 추가
- 회원 탈퇴 완료 시 Alert 창 구현 ( react-toastify )
- 테스트를 위한 임시 api 함수 추가 
비밀번호 변경 기능 수정
- 코드 통일성을 위한 라이브러리 사용 
- useFormik, Yup, react-toastify
- 비밀번호 변경 validate 함수 예외처리 수정 
- 현재 비밀번호가 틀려도 비밀번호가 변경되는 에러 수정 
**Test**🧪
> fix: 내 정보 관리 기능 수정 

- server/src/main/java/com/watchtogether/server/OTT/entity/OttEntity.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/model/InvitePartyForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
- server/src/main/resources/application.yml
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 파티 리스트를 가져오는 기능 구현
- Party 테이블에 invisible, partyFull 칼럼추가
- invisible : 파티를 만들때 초대하는 사람이 있다면 현재시간 +1Days+1Minutes(1분은 더하는 이유는 파티 초대를 받은 사람들이 1days 동안 파티를 수락할수 있는데 미세한 오차가 생길수 있어 1분을 더 추가하여 오류방지)
- partyFull : 파티가 다 찼는지 안찼는지 판단하는 칼럼
- 파티검색시  partyFull 가 false 이고 invisible 이 현재시간과 비교하여 리스트를 가져온다
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 파티리스트 가져오는 기능 구현

- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- fix  : 파티초대원이 없는 경우에도 invisibleDt가 +1days+1minutes 되는것을  현재시간으로 수정
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix  : 파티초대원이 없는 경우에도 invisibleDt가 +1days+1minutes 되는것을 수정

- server/src/main/java/com/watchtogether/server/exception/handler/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/model/LeavePartyForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyMemberRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 파티 나가기 기능 구현
- 파티 나갈시 party 테이블 people 인원 1감소 및 invisible true로 설정
- 파티 나갈시 inviteParty 테이블 에서 삭제
- 파티 나갈시 PartyMember 테이블 에서 삭제
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 파티나기기 기능 구현 및 chore : 단어수정

- server/build.gradle
- server/src/main/java/com/watchtogether/server/components/jwt/JwtAuthenticationFilter.java
- server/src/main/java/com/watchtogether/server/components/jwt/TokenProvider.java
- server/src/main/java/com/watchtogether/server/config/redis/RedisConfig.java
- server/src/main/java/com/watchtogether/server/exception/handler/AuthenticationEntryPointHandler.java
- server/src/main/java/com/watchtogether/server/exception/type/AuthErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/TokenController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/SignOutUser.java
- server/src/main/java/com/watchtogether/server/users/domain/type/UserSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/JwtService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/JwtServiceImpl.java
**개요**
- build : redis 추가
- feat : redis 설정 기능 추가
- feat : Sign-Out 기능 추가
**타입**
**작업 사항**
- 사용자 로그아웃 기능 구현시, 해당 사용자의 access token 값을 redis에 추가한다.
-  access token의 만료기간에서 현재 시간을 뺀 시간도 같이 추가
-  해당 시간이 지나면 redis에서 자동 삭제
- redis에 추가된 access token 값으로 요청이 오면, '로그아웃 처리된 토큰 값입니다' 메시지를 응답
- application-security.yml 파일 추가
- redis host, port 설정
- 각 os 환경에 redis 설치 필요(아래 링크 첨부)
**Test**🧪
- 로그아웃 API 테스트
- [window 환경 redis 설치](https://inpa.tistory.com/entry/REDIS-%F0%9F%93%9A-Window10-%ED%99%98%EA%B2%BD%EC%97%90-Redis-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)
- [mac 환경 redis 설치](https://jsikim1.tistory.com/192)
> feat : 로그 아웃 기능 추가(redis 기능 포함)

- client/src/App.js
- client/src/api/Users.js
- client/src/components/SignIn/FindPassword.jsx
- client/src/components/SignIn/SignIn.jsx
- client/src/components/SignIn/SignIn.styles.jsx
- client/src/pages/ResetPage.jsx
**개요**
비밀번호 찾기 기능 구현
**타입**
**작업 사항**
- code url 페이지 추가 (ResetPage)
- 비밀번호 찾기 관련 api 함수 추가 
- 비밀번호 찾기 모달 구현 
- 로그인 페이지 비밀번호 찾기 버튼 추가 (스타일 일부 수정)
**Test**🧪
> feat: 비밀번호 찾기 기능 구현

- client/src/App.js
- client/src/api/Users.js
- client/src/components/Main/Main.jsx
- client/src/components/Menu/Menu.jsx
- client/src/components/Menu/Menu.styles.jsx
- client/src/components/SignIn/SignIn.jsx
- client/src/index.js
- client/src/pages/MyPage.jsx
- client/src/pages/PartyListPage.jsx
- client/src/pages/PrivateRoutes.jsx
**개요**
feat: JWT 기능 구현 
**타입**
**작업 사항**
- 토큰 만료 시 처리 구현 
- access Token과 refresh Token 분리 ( localStorage / Cookie )
-  Private Route 생성 -> 로그인 인증 여부에 따라 이동 페이지 제한 
+ Menu bar 추가  
**Test**🧪
> feat: JWT 기능 구현 

- server/build.gradle
- server/src/main/java/com/watchtogether/server/exception/type/TokenErrorCode.java
**개요**
- fix : WRONG_REFRESH_TOKEN의 에러 detail 내용 수정
- build : gmail smtp 버전 수정
**타입**
**작업 사항**
- refresh token 값과 Users 테이블에 있는 refresh token 유효성 검사시 에러 메시지 내용 수정
- 수정 전 : "fresh 토큰 값이 일치하지 않습니다."
- 수정 후 : "refresh 토큰 값이 일치하지 않습니다."
- gmail smtp 버전 수정
- 수정 전 : "implementation 'org.springframework.boot:spring-boot-starter-mail:2.7.4'"
- 수정 후 : "implementation 'org.springframework.boot:spring-boot-starter-mail:2.7.5'"
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : WRONG_REFRESH_TOKEN의 에러 detail 내용 수정

- server/src/main/java/com/watchtogether/server/exception/type/UserErrorCode.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- fix : 패스워드 변경시 기존 패스워드 검사
**타입**
**작업 사항**
- 사용자 비밀번호 변경 시, 기존 비밀번호랑 동일한지 여부를 검사한다
-  동일하면 에러 응답 
- SAME_PASSWORD , "기존의 패스워드와 일치합니다."
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 패스워드 변경시 기존 패스워드 검사

- client/src/api/Users.js
- client/src/components/Mypage/PasswordConfirm.jsx
- client/src/components/Mypage/User.jsx
- client/src/components/UserInfo/AlertModal.jsx
- client/src/components/UserInfo/UserInfo.jsx
**개요**
feat: 회원탈퇴 기능 구현 
feat: 마이페이지 기능 추가 
**타입**
**작업 사항**
마이 페이지 기능 추가
- 내 정보 링크 들어가기 전, 비밀번호 한번 더 확인하는 모달 구현 
회원 탈퇴 구현
- 앞서 확인한 비밀번호와 이메일 데이터 토대로 기능 구현 
- 테스트 완료 
**Test**🧪
> feat: 회원탈퇴 기능 구현 

- client/src/components/Mypage/PasswordConfirm.jsx
- client/src/components/UserInfo/AlertModal.jsx
- client/src/components/UserInfo/UserInfo.jsx
**개요**
chore: 회원 탈퇴 에러 수정
**타입**
**작업 사항**
- 비밀번호 데이터가 안넘어가는 이슈 수정 
**Test**🧪
> chore: 회원 탈퇴 에러 수정

- chatServer/src/main/java/com/example/sockettest/ottAuth/components/AppleTvAuth.java
- chatServer/src/main/java/com/example/sockettest/ottAuth/components/TvingAuth.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 자동 로그인 구현, 디즈니, 티빙 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat: 자동 로그인 구현, 디즈니, 티빙 추가

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
fix : 같은사람이 이미 가입한 파티에 가입할 경우 예외처리
**타입**
- []  feat : 새로운 기능 추가
**작업 사항**
- 이미 가입한 파티에 가입할경우 가입하지 못하도록 예외처리
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 같은사람이 이미 가입한 파티에 가입할 경우 예외처리

- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> build : 파티 entity 결제일 추가

- client/src/components/Menu/Menu.styles.jsx
- client/src/components/PartyList/Card.jsx
- client/src/components/PartyList/Card.styles.jsx
- client/src/components/PartyList/PartyList.jsx
- client/src/components/PartyList/PartyList.styles.jsx
- client/src/components/Select/Ott.jsx
- client/src/components/Select/Ott.styles.jsx
- client/src/components/Select/Select.jsx
- client/src/mocks/platform.js
**개요**
refactor: 코드 리팩토링
chore: 스타일 수정 
**타입**
**작업 사항**
select 페이지 
- ott 월 이용료 보이도록 수정 
- 파티장 선택 시 500원, 파티원 선택 시 900원 추가된 금액으로 보여짐 
파티 모집 글 리스트 
- axios 일부 수정, 리액트 쿼리 재사용 
- map을 이용한 코드 리팩토링 
그 외 스타일 수정 및 디자인 일부 수정 
**Test**🧪
> chore: 기능 수정 

- server/src/main/java/com/watchtogether/server/OTT/entity/OttEntity.java
- server/src/main/java/com/watchtogether/server/exception/TransactionException.java
- server/src/main/java/com/watchtogether/server/exception/handler/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/exception/response/TransactionExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/type/TransactionErrorCode.java
- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/domain/dto/TransactionDto.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/Transaction.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/User.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionCharge.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/TransactionRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/type/TransactionResultType.java
- server/src/main/java/com/watchtogether/server/users/domain/type/TransactionSuccess.java
- server/src/main/java/com/watchtogether/server/users/domain/type/TransactionType.java
- server/src/main/java/com/watchtogether/server/users/service/TransactionService.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- feat : 사용자 cash 충전 기능 추가
- feat : User Entity 캐쉬 입금과 출금 기능 추가
- chore : swagger 용 @parameter 추가 
- chore : 불필요한 @column 값 삭제 
- chore : OttEntity 컬럼 명 및 테이블 명 수정
- chore : checkpassword 응답 UserDto로 변경
**타입**
**작업 사항**
- @Parameter(hiddent="true")를 이용하여 swagger에서 불필요한 parameter 값 노출을 제거
- User Entity에 불필요한 @column 어노테이션 제거
- User Entity에서 캐쉬 입금, 출금 로직을 작성하여 불필요한 중복 작업을 없앰
- 사용자가 캐쉬를 충전시키는 기능을 추가함
- 충전할 금액이 0보다 작거나 같으면 에러 응답 ("message": "잘못된 요청입니다.")
**Test**🧪
- 사용자 캐쉬 충전 기능 API 테스트
> feat : 사용자 cash 충전 기능 추가

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/InvitePartyForm.java
- server/src/main/java/com/watchtogether/server/party/domain/model/SendInviteAlertForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- fix : 파티를 만들고 초대한 사람이 있는경우 return값 생성
- return 값은  리스트에 SendInviteAlertForm 형식으로 담아서 넘겨준다.
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티를 만들고 초대한 사람이 있는경우 return값 생성

- server/src/main/java/com/watchtogether/server/party/domain/model/SendInviteAlertForm.java
- server/src/main/java/com/watchtogether/server/party/domain/type/AlertType.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- return 값에 알림타입도 들어갈수 있도록 수정
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : return 값에 알림타입도 들어갈수 있도록 수정

- chatServer/src/main/java/com/example/sockettest/alert/controller/AlertController.java
- chatServer/src/main/java/com/example/sockettest/alert/dto/AlertDto.java
- chatServer/src/main/java/com/example/sockettest/alert/dto/CheckAlertRequest.java
- chatServer/src/main/java/com/example/sockettest/alert/dto/CreateAlertRequest.java
- chatServer/src/main/java/com/example/sockettest/alert/dto/GetAlertListRequest.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/AlertRepository.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/UserRepository.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/Notification.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/User.java
- chatServer/src/main/java/com/example/sockettest/alert/service/AlertService.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- Alert API 구현: createAlert, checkAlert, getAlertList
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> Feat: Alert API 구현

- client/src/App.js
- client/src/components/Alarm/Alarm.jsx
- client/src/components/Alarm/Alarm.styles.jsx
- client/src/components/Alarm/MessageModal.jsx
- client/src/components/Alarm/Pagination.jsx
- client/src/components/Alarm/Pagination.styles.jsx
- client/src/components/Menu/Menu.jsx
- client/src/components/Menu/Menu.styles.jsx
- client/src/components/Modal/Modal.styles.jsx
- client/src/mocks/alerts.js
- client/src/pages/AlarmPage.jsx
**개요**
feat: 쪽지함 페이지 마크업 
**타입**
**작업 사항**
- Menu bar 수정 -> 읽지 않은 메세지 개수 bedge 표시 
- 쪽지함 페이지 추가 
- 페이지네이션 추가
- 메세지 클릭 시 모달로 보이게끔 구현  
**Test**🧪
<div>
</div>
> feat: 쪽지함 페이지 마크업 

- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/domain/dto/TransactionDto.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/Transaction.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionCharge.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionList.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/TransactionRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/type/TransactionSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/TransactionService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
**개요**
- feat : 사용자 거래 내역 리스트 출력 기능 추가
- fix : transaction table 컬럼명 변경 
- fix : transactino Entity 데이터 타입 변경 
**타입**
**작업 사항**
- 사용자 거래 내역 리스트 출력 기능 추가
- transactionResultType과 transactionType 데이터 타입 enum에서 String 타입으로 변경
- traderNickname에서 traderEmail로 변경
**Test**🧪
- 사용자 거래 내역 리스트 출력 API 테스트
> feat : 사용자 거래 내역 리스트 출력 기능 추가

- server/src/main/java/com/watchtogether/server/exception/OttException.java
- server/src/main/java/com/watchtogether/server/exception/handler/CustomExceptionHandler.java
- server/src/main/java/com/watchtogether/server/exception/response/OttExceptionResponse.java
- server/src/main/java/com/watchtogether/server/exception/type/OttErrorCode.java
- server/src/main/java/com/watchtogether/server/exception/type/UserErrorCode.java
- server/src/main/java/com/watchtogether/server/ott/domain/dto/OttDto.java
- server/src/main/java/com/watchtogether/server/ott/domain/entity/BaseEntity.java
- server/src/main/java/com/watchtogether/server/ott/domain/entity/Ott.java
- server/src/main/java/com/watchtogether/server/ott/domain/repository/OttRepository.java
- server/src/main/java/com/watchtogether/server/ott/service/Impl/OttServiceImpl.java
- server/src/main/java/com/watchtogether/server/ott/service/OttService.java
- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionWithdraw.java
- server/src/main/java/com/watchtogether/server/users/domain/type/TransactionSuccess.java
- server/src/main/java/com/watchtogether/server/users/service/Application/TransactionApplicaion.java
- server/src/main/java/com/watchtogether/server/users/service/TransactionService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
**개요**
- feat : transaction 선결제 기능 추가
- feat : ott 찾기 기능 추가
**타입**
**작업 사항**
- 사용자가 파티 참가 시, 선결제 기능 추가
- 사용자의 캐쉬가 부족하면 에러 메시지 응답
- ottId로 ott 서비스 찾기 기능 추가
**Test**🧪
- 사용자 선결제 기능 추가
> feat : transaction 선결제 기능 추가

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/SendInviteAlertForm.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
feat : (메시지 클릭시 호출하는 api) 메시지 클릭시 파티를 계속하겠다는 check 컬럼을 true로 바꿔주는 기능 추가
fix : 파티 생성시 return값에 리더닉네임 값 추가
fix : 파티 생성시 알림return값에 리더닉네임 값 추가
**타입**
**작업 사항**
-(메시지 클릭시 호출하는 api) 메시지 클릭시 파티를 계속하겠다는 check 컬럼을 true로 바꿔주는 기능 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : (메시지 클릭시 호출하는 api) 메시지 클릭시 파티를 계속하겠다는 check 컬럼을 true로 바꿔주는 기능 추가

- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/service/Application/TransactionApplicaion.java
- server/src/main/java/com/watchtogether/server/users/service/TransactionService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
**개요**
- feat : transaction 선결제 취소 기능 추가
**타입**
**작업 사항**
- 사용자가 파티 탈퇴 시 선결제 금액 취소 기능 추가
**Test**🧪
- 선결제 취소 API 테스트
> feat : transaction 선결제 취소 기능 추가

- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/type/AlertType.java
**개요**
chore : check가 예약어여서 테이블 생성불가하여 alertCheck으로 변경
**타입**
**작업 사항**
- check가 예약어여서 테이블 생성불가하여 alertCheck으로 변경
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : check가 예약어여서 테이블 생성불가하여 alertCheck으로 변경

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/InviteParty.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/model/SendAlertForm.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
feat : 파티 ott비밀번호 변경 기능 추가
fix : 파티 에러 추가
chore : 필요없는 import문 삭제
**타입**
**작업 사항**
- 파티 ott비밀번호 변경 기능 추가
-  파티 에러 추가
- 필요없는 import문 삭제
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 파티 ott비밀번호 변경 기능 추가

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/model/SendAlertForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
feat : 자동으로 메세지 전송, 결제, 파티 수락체크 판별기능 추가
**타입**
**작업 사항**
- 자동으로 메세지 전송, 결제, 파티 수락체크 판별기능 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat : 자동으로 메세지 전송, 결제, 파티 수락체크 판별기능 추가

- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/domain/dto/TransactionDto.java
- server/src/main/java/com/watchtogether/server/users/domain/entitiy/Transaction.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionCharge.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionWithdraw.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/TransactionRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/UserRepository.java
- server/src/main/java/com/watchtogether/server/users/service/Application/TransactionApplicaion.java
- server/src/main/java/com/watchtogether/server/users/service/TransactionService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
**개요**
- feat : 파티장 거래 입금과 파티장과 파티원 거래내역 추가 및 변경 기능
- fix : transaction Entity partyId 추가 및 traderEmail -> traderNickname으로 변경
- 
**타입**
**작업 사항**
- 파티 참가 시, 파티 정원이 4명인 경우 파티장에게 파티원(1인 * 이용료 - 수수료) * 3 의 금액 입금
- 파티장 거래 내역 추가 및 파티원들의 거래내역결과 값을 '대기' 에서 '완료'로 변경
- cron기능으로 해당 기간에 위와 동일한 기능 구현
**Test**🧪
- 결제 입금 API 테스트 완료
> feat : 파티장 거래 입금과 파티장과 파티원 거래내역 추가 및 변경 기능

- chatServer/src/main/java/com/example/sockettest/alert/dto/CreateAlertRequest.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/AlertRepository.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/PartyRepository.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/UserRepository.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/InviteParty.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/Notification.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/Party.java
- chatServer/src/main/java/com/example/sockettest/alert/persist/entity/PartyMember.java
- chatServer/src/main/java/com/example/sockettest/alert/service/AlertService.java
- server/src/main/java/com/watchtogether/server/alert/controller/AlertController.java
- server/src/main/java/com/watchtogether/server/alert/dto/AlertDto.java
- server/src/main/java/com/watchtogether/server/alert/dto/CheckAlertRequest.java
- server/src/main/java/com/watchtogether/server/alert/dto/CreateAlertRequest.java
- server/src/main/java/com/watchtogether/server/alert/dto/GetAlertListRequest.java
- server/src/main/java/com/watchtogether/server/alert/persist/AlertRepository.java
- server/src/main/java/com/watchtogether/server/alert/persist/entity/Notification.java
- server/src/main/java/com/watchtogether/server/alert/service/AlertService.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/UserRepository.java
- server/src/main/resources/application.yml
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- Alert API 구현
- 해당 Alert API Server 모듈로 코드 이전
- UserRepository 파일 내 merge 이슈 해결
- PartRepository 파일 내 merge 이슈 해결
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> Alert API 구현 및 Server 모듈로 코드 이전

- server/build.gradle
- server/src/main/java/com/watchtogether/server/config/SecurityConfig.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/AppleTvAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/DisneyAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/NetflixAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/OttAuthComponent.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/TvingAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/WatchaAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/components/WavveAuth.java
- server/src/main/java/com/watchtogether/server/ottAuth/controller/OttAuthController.java
- server/src/main/java/com/watchtogether/server/ottAuth/domain/LoginResult.java
- server/src/main/java/com/watchtogether/server/ottAuth/domain/OttAuthRequest.java
- server/src/main/java/com/watchtogether/server/ottAuth/service/OttAuthService.java
- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- OttAuth Api 구현
- chatServer -> server로 코드 이전
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> feat: OttAuth Api 구현

- server/src/main/java/com/watchtogether/server/alert/dto/AlertDto.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- alert/list api 스팩 변경
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
**Others - optional**![image](https://user-images.githubusercontent.com/58586521/200325185-f477211b-1a5c-4840-8e7e-9ceb551ad7ef.png)
> fix: alert/list api 스팩 변경

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
- server/src/main/java/com/watchtogether/server/users/controller/TransactionController.java
- server/src/main/java/com/watchtogether/server/users/domain/model/TransactionWithdraw.java
- server/src/main/java/com/watchtogether/server/users/domain/repository/TransactionRepository.java
- server/src/main/java/com/watchtogether/server/users/service/Application/TransactionApplicaion.java
- server/src/main/java/com/watchtogether/server/users/service/impl/TransactionServiceImpl.java
- server/src/main/resources/application.yml
**개요**
- fix : transaction deposit 기능 수정
- fix : Party Service transaction deposit 부분 수정
**타입**
**작업 사항**
- 모든 정원 4명이 되고 파티 방 생성 시, 파티원들의 거래 내역 에러 수정
- partyId와 거래결과 유효성 결과 후 해당 거래내역의 거래결과만 완료로 수정
- 파티 참가 시, 해당 파티에 속해있는 지 유효성 검사 추가
-
**Test**🧪
- transactino deposit API 테스트 완료
> fix : transaction deposit 기능 수정

- chatServer/src/main/java/com/example/sockettest/api/ChatController.java
- server/src/main/java/com/watchtogether/server/alert/controller/AlertController.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- api/v1/chat(GET) 스팩 변경
- api/alert/list(GET) 스팩 변경
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
-api/v1/chat(GET)
- 변경 전
- 변경 후
- api/alert/list(GET)
- 변경 전
-변경 후
> fix: api/v1/chat(GET), api/alert/list(GET) 스팩 변경

- server/src/main/java/com/watchtogether/server/alert/service/AlertService.java
- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/model/ChangePasswordForm.java
- server/src/main/java/com/watchtogether/server/party/domain/model/CheckInviteMessageForm.java
- server/src/main/java/com/watchtogether/server/party/domain/model/LeavePartyResponseForm.java
- server/src/main/java/com/watchtogether/server/party/domain/type/AlertType.java
- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 알림타입 추가
- 파티 나가는 기능을 파티장이 나갈때와 파티원이 나갈때로 분리
- 파티장이 나가는 경우 파티 삭제
- 파티원이 나가는 경우 파티원수 -1 및 메세지 전송
- 메시지를 switch문으로 세분화 하여 전송
- 데이터를 받고 반환할수 있는 폼 작성
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티 나가는 기능 분리 데이터 폼 작성

- client/package-lock.json
- client/package.json
- client/src/api/Alert.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/Alarm/Alarm.jsx
- client/src/components/Menu/Menu.jsx
- client/src/components/Menu/Menu.styles.jsx
- client/src/pages/PrivateRoutes.jsx
**개요**
feat: 쪽지함 기능 추가 
**타입**
**작업 사항**
- 파티 모집 글 등록 시 초대된 사용자에게 alert 메시지 전송 
- 메뉴 바 랜더링 시 메시지 가져오기 
- 메시지중 안읽은 메시지 갯수 필터링 bedge로 보여줌 
**Test**🧪
> feat: 쪽지함 기능 추가 

- client/src/api/OttAuth.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/Menu/Menu.jsx
- client/src/components/PartyList/Card.jsx
- client/src/components/PartyList/PartyList.jsx
- client/src/components/Payment/Payment.jsx
- client/src/mocks/platform.js
**개요**
feat: 크롤링 기능 추가 
chore: 오탈자 수정 
**타입**
**작업 사항**
- ottAuth api 연결 
-> 넷플릭스 크롤링 테스트 완료 
- 오탈자 수정 
**Test**🧪
- 테스트 의도
> feat: 크롤링 기능 추가 

- client/src/App.js
- client/src/components/Chat/Chat.jsx
- client/src/components/Chat/Chat.styles.jsx
- client/src/mocks/chatTest.js
- client/src/pages/ChatPage.jsx
**개요**
feat: 채팅 페이지 마크업
**타입**
**작업 사항**
- 채팅 페이지 마크업 
**Test**🧪
> feat: 채팅 페이지 마크업

- server/src/main/java/com/watchtogether/server/alert/dto/AlertDto.java
- server/src/main/java/com/watchtogether/server/ott/components/AppleTvAuth.java
- server/src/main/java/com/watchtogether/server/ott/components/DisneyAuth.java
- server/src/main/java/com/watchtogether/server/ott/components/NetflixAuth.java
- server/src/main/java/com/watchtogether/server/ott/components/OttAuthComponent.java
- server/src/main/java/com/watchtogether/server/ott/components/TvingAuth.java
- server/src/main/java/com/watchtogether/server/ott/components/WatchaAuth.java
- server/src/main/java/com/watchtogether/server/ott/components/WavveAuth.java
- server/src/main/java/com/watchtogether/server/ott/controller/OttAuthController.java
- server/src/main/java/com/watchtogether/server/ott/domain/dto/LoginResult.java
- server/src/main/java/com/watchtogether/server/ott/domain/dto/OttAuthRequest.java
- server/src/main/java/com/watchtogether/server/ott/service/OttAuthService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
- []  feat : 새로운 기능 추가
**작업 사항**
- alarm-list 응답 메시지에 uuid 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix: alarm-list 응답 메시지에 uuid 추가

- client/src/api/Parties.js
- client/src/components/AddParty/AddParty.jsx
- client/src/components/Alarm/MessageModal.jsx
**개요**
feat: 알림 수락 기능 추가
**타입**
**작업 사항**
**Test**🧪
> feat: 알림 수락 기능 추가

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
ott_Id 가 null 값일경우 에러처리
**타입**
**작업 사항**
- ott_Id 가 null 값일경우 OTT_ID_NOT_FOUND 에러 반환
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : ott_Id 가 null 값일경우 에러처리

- client/src/api/Parties.js
- client/src/components/MyParty/Card.jsx
- client/src/components/MyParty/Card.styles.jsx
- client/src/components/MyParty/MyParty.jsx
- client/src/components/Payment/Card.styles.jsx
**개요**
- chore: 컴포넌트 서식 및 코드 오류에 대한 자잘한 수정
**타입**
**작업 사항**
- 오류가 나지 않게 컴포넌트 서식 및 코드 오류에 대한 수정을 진행했습니다. 
**Test**🧪
> chore: 컴포넌트 서식 및 코드 오류에 대한 자잘한 수정

- server/src/main/java/com/watchtogether/server/alert/controller/AlertController.java
- server/src/main/java/com/watchtogether/server/ott/controller/OttAuthController.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- swagger이용하여 명세서 작성
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> swagger이용하여 명세서 작성

- client/src/components/AddParty/AddParty.jsx
- client/src/components/Alarm/MessageModal.jsx
- client/src/components/Chat/Chat.jsx
**개요**
chore: 채팅방, 알림 기능 수정 
**타입**
**작업 사항**
- 채팅방 기능 수정 
- 알림 메시지 내용 수정 
**Test**🧪
> chore: 채팅방, 알림 기능 수정 

- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- fix : 내파티 목록에 대기중인 파티데이터도 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 내파티 목록에 대기중인 파티데이터도 추가

- server/src/main/java/com/watchtogether/server/exception/type/PartyErrorCode.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyMemberRepository.java
**개요**
- chore : 에러코드 및 검색구문 추가
**타입**
**작업 사항**
- 에러 코드 추가
- partymember 검색구문 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : 에러코드 및 검색구문 추가

- client/src/components/Alarm/MessageModal.jsx
**개요**
chore: 알람 기능 수정
**타입**
**작업 사항**
- 수락하기 이후 정상적으로 로직이 수행될 경우 파티에 가입되었다는 알림 출력
**Test**🧪
> chore: 알람 기능 수정

- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/model/ChangePasswordForm.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
fix : form에서 데이터 null 로 되는 버그 수정
**타입**
**작업 사항**
- form에 @Setter 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : form에서 데이터 null 로 되는 버그 수정

- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
fix : 파티 모집완료시 3명만 저장되는  버그 수정
**타입**
**작업 사항**
-  레파지토리 검색후 작업을 바로 리스트에서 작업할수 있도록 수정
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티 모집완료시 3명만 저장되는  버그 수정

- client/src/components/Alarm/Alarm.jsx
- client/src/components/Alarm/Alarm.styles.jsx
- client/src/components/Alarm/MessageModal.jsx
- client/src/components/Menu/Menu.jsx
**개요**
fix: 메뉴바 bedge 기능 수정
**타입**
**작업 사항**
- 안 읽은 알림 메시지 수가 바로 안뜨는 오류 수정
**Test**🧪
> fix: 메뉴바 bedge 기능 수정

- client/src/components/MyParty/MyPartyDetail.jsx
- client/src/components/MyParty/PasswordModal.jsx
**개요**
- chore: 계정 비밀번호 오탈자 수정
**타입**
**작업 사항**
- 계정 비밀번호에서 보내는 값을 잘못 잡는 부분이 있어서 수정했습니다.
**Test**🧪
> chore: 계정 비밀번호 오탈자 수정

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
**개요**
fix : @RequestBody 추가
**타입**
**작업 사항**
- 컨트롤러에서  @RequestBody 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : @RequestBody 추가

- server/src/main/java/com/watchtogether/server/ServerApplication.java
- server/src/main/java/com/watchtogether/server/alert/persist/AlertRepository.java
- server/src/main/java/com/watchtogether/server/alert/service/AlertService.java
- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/PartyMember.java
- server/src/main/java/com/watchtogether/server/party/domain/model/ChangePasswordForm.java
- server/src/main/java/com/watchtogether/server/party/domain/model/CheckContinueMessageForm.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- fix : 메크로 버그 수정
- jpa 구문 추가
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 메크로 버그 수정

- server/src/main/java/com/watchtogether/server/alert/persist/AlertRepository.java
- server/src/main/java/com/watchtogether/server/alert/service/AlertService.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/InvitePartyRepository.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/PartyService.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
- server/src/main/java/com/watchtogether/server/users/service/Application/DeleteUserApplication.java
**개요**
- fix : 회원 탈퇴 전 파티원인경우, 파티장인경우에 따라 Alert 내역 지우기
- fix : 회원 탈퇴 전 파티원인경우, 파티장인경우에 따라 Party 및 InviteParty 내역 제거
- fix : 회원 탈퇴 전 Party, InviteParty 와 Alert 내역 제거 추가
**타입**
- []  feat : 새로운 기능 추가
**작업 사항**
- 회원 탈퇴 전 Party, InviteParty 와 Alert 내역을 제거
- 파티장인경우와 파티원인경우를 나누어 유효성 검사 및 처리
**Test**🧪
- 회원 탈퇴 전 Party, InviteParty 와 Alert 내역을 제거API 테스트
> fix : 회원 탈퇴전 Party, InviteParty 와 Alert 내역 제거 추가

- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티 참가 전, 사용자 거래 내역 확인

- client/src/App.js
- client/src/api/Chat.js
- client/src/components/Chat/Chat.jsx
- client/src/pages/ChatPage.jsx
- client/src/store/Chat.js
- client/src/store/index.js
**개요**
chore: 채팅 기능 수정
**타입**
**작업 사항**
- 채팅 이슈 수정 
**Test**🧪
> chore: 채팅 기능 수정

- server/src/main/java/com/watchtogether/server/users/service/Application/DeleteUserApplication.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- fix : 파티 탈퇴 기능 수정
**타입**
**작업 사항**
- 회원 탈퇴 기능 수정.
**Test**🧪
- 회원 탈퇴 기능 수정 테스트 API
> fix : 회원 탈퇴 기능 수정

- client/src/api/Users.js
**개요**
test: 배포 관련 axios 테스트
**타입**
**작업 사항**
baseUrl 추가 
**Test**🧪
> test: 배포 관련 axios 테스트

- client/netlify.toml
- client/src/api/Users.js
- client/src/components/Chat/Chat.jsx
- client/src/setupProxy.js
- client/src/store/index.js
**개요**
chore: 서버 url 로컬로 변경
**타입**
**작업 사항**
**Test**🧪
> chore: 서버 url 로컬로 변경

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/entitiy/Party.java
- server/src/main/java/com/watchtogether/server/party/domain/model/CreateChatForm.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
fix : 파티 채팅창 생성여부 변수 및 메소드 설정
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티 채팅창 생성여부 변수 및 메소드 설정

- server/src/main/java/com/watchtogether/server/users/controller/TokenController.java
**개요**
- fix : 로그아웃 url 변경
**타입**
**작업 사항**
- 로그아웃 url 변경
/api/v1/sign-out -> /api/v1/users/sign-out
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 로그아웃 url 변경

- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
**개요**
chore : 스케쥴 시간 조정
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : 스케쥴 시간 조정

- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
chore : checkPartyFull @Transactional 추가
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : checkPartyFull @Transactional 추가

- server/src/main/java/com/watchtogether/server/party/controller/PartyController.java
- server/src/main/java/com/watchtogether/server/party/domain/repository/PartyRepository.java
- server/src/main/java/com/watchtogether/server/party/service/impl/PartyServiceImpl.java
**개요**
fix : 파티방 일괄 false 로 수정하는 api
**타입**
**작업 사항**
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : 파티방 일괄 false 로 수정하는 api

- client/src/api/Chat.js
- client/src/components/Chat/Chat.jsx
- client/src/setupProxy.js
**개요**
build : 채팅 서버 url 변경 
**타입**
**작업 사항**
- 로컬 -> 서버 URL 변경 
**Test**🧪
> build : 채팅 서버 url 변경 

- client/src/components/AddParty/AddParty.jsx
- client/src/components/AddParty/SearchModal.jsx
**개요**
fix: 파티원 초대 기능 수정
**타입**
**작업 사항**
- 파티원 초대 시 사용자 본인 닉네임 검색시 초대 되는 에러 수정 
**Test**🧪
> fix: 파티원 초대 기능 수정

- server/src/main/java/com/watchtogether/server/party/service/Application/CheckPartyApplication.java
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
chore : 메세지 수정
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> chore : 메세지 수정

- server/src/main/java/com/watchtogether/server/users/controller/UserController.java
- server/src/main/java/com/watchtogether/server/users/service/Application/DeleteUserApplication.java
- server/src/main/java/com/watchtogether/server/users/service/UserService.java
- server/src/main/java/com/watchtogether/server/users/service/impl/UserServiceImpl.java
**개요**
- fix : DeleteUser 파라미터 값 변경
**타입**
**작업 사항**
- DeleteUser 파라미터 값 email로 변경
**Test**🧪
- 간단한 테스트 내용
- 테스트 의도
> fix : DeleteUser 파라미터 값 변경

- client/src/components/MyParty/MyParty.styles.jsx
- client/src/components/Payment/Card.jsx
- client/src/components/Payment/PaymentList.styles.jsx
- client/src/components/SignIn/SignIn.styles.jsx
**개요**
chore: 에러 및 스타일 수정
**타입**
**작업 사항**
**Test**🧪
> chore: 에러 및 스타일 수정

- server/src/main/java/com/watchtogether/server/components/jwt/TokenProvider.java
- server/src/main/java/com/watchtogether/server/exception/handler/AuthenticationEntryPointHandler.java
**개요**
- refactor : null 값 처리 와 equals() 처리
**타입**
**작업 사항**
- SonarQube를 통해 버그 확인 후, 리팩토리 처리
- null 값 처리 와 equals() 처리
**Test**🧪
- toekn API 테스트
> refactor : null 값 처리 와 equals() 처리

- client/src/api/Chat.js
- client/src/api/OttAuth.js
- client/src/api/Parties.js
- client/src/api/Transaction.js
- client/src/api/User.js
- client/src/components/SignIn/SignIn.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/components/SignUp/SignUp.styles.jsx
- client/src/setupProxy.js
**개요**
- fix: 코드 리팩토링 (서식 및 모션 수정)
**타입**
**작업 사항**
- 로그인, 회원가입 컴포넌트에 모션을 추가했습니다.
- 회원가입 컴포넌트의 서식을 작은 수준 수정했습니다.
- 로그인 입력란에 placeholder를 추가했습니다. (원하시면 다시 빼도 괜찮습니다.)
**Test**🧪
> fix: 코드 리팩토링 (서식 및 모션 수정)
